apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp.fullname" . }}-tss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- tpl (toYaml .Values.deployment.annotations) . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sdp.selectorLabels" . | nindent 6 }}

  {{- if .Values.deployment.strategy }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  {{- end }}
  
  template:
    metadata:
      {{- if .Values.deployment.tssPodAnnotations }}
      annotations:
        {{- tpl (toYaml .Values.deployment.tssPodAnnotations) . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ tpl .Values.serviceAccount.name $ }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      
      containers:
      # ============================= Stellar Disbursement Platform: =============================
        - name: {{ .Chart.Name }}-tss
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.ephemeralDatabase }}
          env:
            - name: DATABASE_URL
              value: 'postgres://postgres:postgres@{{ include "sdp.fullname" . }}-psql.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres-sdp?sslmode=disable'
          {{- end }}
          args:
            - "tss"
          ports:
            - name: http
              containerPort: {{ include "tss.port" . }}
              protocol: TCP
            - name: metrics
              containerPort: {{ include "tss.metricsPort" . }}
              protocol: TCP

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          envFrom:
          - configMapRef:
              name: {{ include "sdp.fullname" . }}-tss
          
          {{- if .Values.secretName }}
          - secretRef:
              name: {{ .Values.secretName }}
          {{ end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
